name: Angular Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install frontend dependencies
      working-directory: ./class-voting-frontend
      run: npm ci

    - name: Build Angular frontend
      working-directory: ./class-voting-frontend
      run: npm run build -- --prod

    - name: Run Angular tests
      working-directory: ./class-voting-frontend
      run: npm test -- --watch=false --browsers=ChromeHeadless
